export const products = [
  {
    id: 1,
    title: "espresso",
    price: 380,
    stock: 5,
    description: "Espresso clásico",
    category: "cafe",
    img: "https://res.cloudinary.com/duxqgahbk/image/upload/v1678584347/espresso_xrpvxx.jpg",
  },
  {
    id: 2,
    title: "Cappuccino",
    price: 550,
    stock: 5,
    description: "Shot de espresso con leche texturizada y espuma de leche",
    category: "cafe",
    img: "https://res.cloudinary.com/duxqgahbk/image/upload/v1678562398/cappuccino_mlsuwo.jpg",
  },
  {
    id: 3,
    title: "Vienés",
    price: 570,
    stock: 5,
    description: "Doble shot espresso con espuma de leche y crema batida",
    category: "cafe",
    img: "https://res.cloudinary.com/duxqgahbk/image/upload/v1678579340/vienes_eyst5m.jpg",
  },
  {
    id: 4,
    title: "Bombón Ethiopia",
    price: 820,
    stock: 5,
    description:
      "Shot de espresso, leche condensada, leche texturizada y barra de chocolate",
    category: "cafe",
    img: "https://res.cloudinary.com/duxqgahbk/image/upload/v1678579359/bombonEtiopia_h8njpf.jpg",
  },
  {
    id: 5,
    title: "Spicey Honey",
    price: 600,
    stock: 5,
    description:
      "Doble ristretto, jarabe de miel, garam masala y leche texturizada",
    category: "cafe",
    img: "https://res.cloudinary.com/duxqgahbk/image/upload/v1678562422/spiceyHoney_azcnqs.jpg",
  },
  {
    id: 6,
    title: "Espresso Tonic",
    price: 820,
    stock: 5,
    description:
      "Doble shot de espresso con tónica y rodaja de naranja, pomelo o limón",
    category: "cafeFrio",
    img: "https://res.cloudinary.com/duxqgahbk/image/upload/v1678584707/espressoTonic_yhnhzg.jpg",
  },
  {
    id: 7,
    title: "Affogato",
    price: 880,
    stock: 5,
    description: "Doble shot de espresso con dos bochas de helado de vainilla",
    category: "cafeFrio",
    img: "https://res.cloudinary.com/duxqgahbk/image/upload/v1678562370/affogato_pcncmq.jpg",
  },
  {
    id: 8,
    title: "Filtrado Frio",
    price: 730,
    stock: 5,
    description: "Filtrado por goteo o inmersión durante 18hs.",
    category: "cafeFrio",
    img: "https://res.cloudinary.com/duxqgahbk/image/upload/v1678562416/filtradoFrio_hbrzym.jpg",
  },
  {
    id: 9,
    title: "Licuado",
    price: 700,
    stock: 5,
    description:
      "Banana, Frutilla, Frutos rojos, Mango o Maracuya (al agua o con leche)",
    category: "bebidas",
    img: "https://res.cloudinary.com/duxqgahbk/image/upload/v1678562419/licuado_rccsdu.jpg",
  },
];
